- hosts: Kubernetes_Master
  becom: yes
  gather_facts: false
  tasks:
   - name: get join command
     shell: kubeadm token create --print-join-command
     register: join_command_raw

   - name: Register dummy host with variable it access in next play
     add_host: 
       name: "DUMMY_HOST"
       JOIN_COMMAND: "{{join_command_raw.stdout}}"

- hosts: Kubernetes_Worker
  becom: yes
  tasks:
  - name: join cluster
    shell: "{{ hostvars['DUMMY_HOST'] ['JOIN_COMMAND'] }} >> node.join.txt"
    args:
      chdir: $HOME
      creates: node.join.txt

  
   